title: Leap Day theme
description: Leap Day is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
include: ["_pages"]
permalink: date
paginate: 5
paginate_path: "/prime-news/page:num"

plugins_dir:
  - jekyll-paginate

sass:
    load_paths:
        - _sass
        - node_modules

gems: [jekyll-paginate]

exclude: []

