title: Starxpert Blog
description: Blog technique straxpert.
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
include: ["_pages"]
permalink: date
paginate: 5
paginate_path: "/prime-news/page:num"

plugins_dir:
  - jekyll-paginate

sass:
    load_paths:
        - _sass
        - node_modules

gems: [jekyll-paginate]

exclude: []

